services:
  test-api:
    image: api
    ports:
      - "55555:55555"
    build:
      context: .
      dockerfile: API/Dockerfile
    networks:
      - default
    labels:
      - "com.prometheus.enable=true"
      - "com.prometheus.port=55555"

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default
        
  grafana:
    image: grafana/grafana:11.2.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      

  alertmanager:
    image: prom/alertmanager:v0.21.0
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    container_name: alertmanager
    hostname: alertmanager
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    networks:
      - default
        
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16