global:
  scrape_interval: 1s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'app-reader'
    static_configs:
      - targets: ['test-api:55555', 'localhost:55555']
