# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker setup
      uses: docker/setup-buildx-action@v3.8.0
    - name: docker build
      run: docker build --file /API/Dockerfile .
    - name: image push
      run: docker build --file /API/Dockerfile .
        
